services:
  haoran:
    image: haoran:latest
    container_name: haoran
    restart: unless-stopped
    environment:
      CONFIG_FILE_PATH: /etc/bot/config.yaml
    volumes:
      - /path/to/config:/etc/bot
      - /path/to/ms-playwright:/ms-playwright
